### ISSUE TITLE
Johto is spelled wrong

### ISSUE THREAD

**Issue by muffinjets** [KittyPBoxx/GBAXG#1]
Not sure if it's maybe spelled different in different areas of the world, but you do know that it's spelled "Johto", right?

**Comment by muffinjets** [comment]
https://bulbapedia.bulbagarden.net/wiki/Johto

**Comment by KittyPBoxx** [comment]
Display strings an readme should be fixed. The element id's, flags and map visualizer will need testing before I can push an update

**Comment by KittyPBoxx** [comment]
I've fixed the names in code. Because it effects the config save data I've also applied a patch to the current live build as well. The seed files in the repo have been updated but the new build should be backwards compatible with any saves and seeds generated before the change.
