### ISSUE TITLE
Adding a keybind for emulation speedup

### ISSUE THREAD

**Issue by keanfreeman** [KittyPBoxx/GBAXG#13]
Hi there,

Since GBAXG supports emulation speedup, it would be nice to be able to bind a key/controller button to toggle that on and off for convenience. Additionally, a similar keybind that only enables the speedup when a button's being held would be useful too. These sorts of bindings are really nice for these kinds of games.

Thank you.

**Comment by KittyPBoxx** [comment]
This shouldn't be too hard to add. 

Notes for future future me trying to add this:
> You wrote some code ages ago that can be run in the browser console for 'hold-space-to-speedup'
> 
> `window.addEventListener("keydown", e => e.code == "Space" && GBAXG.exposedEmulationCore.setSpeed_EmulationCore(5));window.addEventListener("keyup", e => e.code == "Space" && GBAXG.exposedEmulationCore.setSpeed_EmulationCore(1))`
> 
> For a proper fix all you need to do is in sky-core/web-src add an entry  to `Command.js` and `Keybind.js` . The keybind reload should now work to pick this up without clearing cache?

**Comment by KittyPBoxx** [comment]
The following key binds are now added:

- Toggle Speedup (default key 't')
- Hold Down for speedup (default key 'h')

Hard refreshing the page may be required to pick up the new code as I've not increased the version number for this.
