### ISSUE TITLE
Ruins of Alph chamber Softlock

### ISSUE THREAD

**Issue by RubyTiger18** [KittyPBoxx/GBAXG#2]
I went into a warp area (It was actually the museum in Pewter), i got sent down to the unown area of the ruins of alph. There was just one ladder, the ladder lead to a dead end. I know there's a way to materialize an escape rope in your inventory, but if someone wants to play with as little handicaps as possible it would be a small hassle

**Comment by KittyPBoxx** [comment]
Next version of the randomization algorithm should prevent getting stuck by one way warps. I think in the current version there should be a "warp" option at the bottom of the start menu to get out of situation where you get stuck?

**Comment by RubyTiger18** [comment]
is that what that warp thing is for (Tinkers with it, and gets out of new area i got stuck in) OH SNAPS!!! This is amazing!
