### ISSUE TITLE
Rewrite Bike Sprite for Crystal Acro Bike

### ISSUE THREAD

**Issue by TheT113** [KittyPBoxx/GBAXG#3]
I know this seems like a minor thing, but... I greatly prefer to use the Acro Bike in Crystal and Emerald, due to it just not whipping wildly out of control. For that reason, I can't even use the "Bike Everywhere" cheats, since they default to Mach Bike.

So when using the Acro Bike in Crystal, it uses a Crystal sprite currently, instead of using Leaf. (I've only tested this on girl sprite, obviously.)

Humbly requesting this be changed to be in line with the other bike sprites!

Also, this has been really wild to play and I'm super into it, even though I still haven't found any of the 3 first Gyms...

**Comment by KittyPBoxx** [comment]
Released version 0.9.21-Alpha so if you refresh the page the main Acro Bike Sprites should now be working in crystal. 
Sprites for wheelies and trick jumps are still not done yet for (in Emerald or Crystal) as Fire Red has no equivalent sprites so this would probably need custom art.

**Comment by KittyPBoxx** [comment]
The new release now has acro bike sprite work for crystal and emerald.
