### ISSUE TITLE
Softlock where you can't beat Stephen 

### ISSUE THREAD

**Issue by yoitsyohane** [KittyPBoxx/GBAXG#4]
Steven was on Route 35 which you need access to one of the other two routes to get to it, because the sudowoodo has to be moved from that side, but the other two entrances were two one ways making it impossible, seed was rdywoj

**Comment by KittyPBoxx** [comment]
I'm assuming the checksum you have is 320AA6D5 and that that you're playing on the old version?

If this is the case can I ask how you ended up using it? Is there a link I need to update somewhere e.t.c?
Definitely recommend the new version https://kittypboxx.github.io/GBAXG/skycore/build/bin/ as there have been a lot of improvements. Including changes designed to make it less frustrating and lots of the useless deadends get removed by default. 

If that checksum is right then the intended way to get to Steven is to get the 'Wailmer Pail' by taking to the 2nd girl in Rustboro Flower Shop. This can be found in Goldenrod Magnet Train station (right of radio tower, via a seafoam island corridor). Once you have the 'Wailmer Pail' this can be used to remove the Sudowoodo  from either Ecruteak or Violet side.

**Comment by yoitsyohane** [comment]
Thanks for the reply and solution! 
I believe I was using the older version, the link I clicked that has the outdated version is here: https://kittypboxx.github.io/GBAXG/
Under Setup Step 4 it has the outdated link

**Comment by KittyPBoxx** [comment]
No worries. I have spoiler log tools, they're not available yet because they need some work.

The new version was only released this month. I must have missed updating the setup tutorial text. Will close the issue now as I've updated the tutorial text and added a popup on the older versions page.
