### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by michalgorkowski2020** [KittyPBoxx/GBAXG#5]
Hello Kitty.

I am having trouble running the updated version of GBAXG on MacOS. When launching the randomizer, the load screen for FR loads, but the randomizer does not launch past the Charizard opening screen and makes the same static sound GBA makes when you accidentally remove the cartridge from a physical console.

Each of the roms works individually in VisualBoy Advance, so it's not a problem with the roms. Also, using the outdated version 0.10.4-Alpha link with the same roms works fine, this is only a problem in the updated 1.0.2-Alpha version of the emulator.

I tried Clear Saves/ROMS and Clear Stored ROMS many times and nothing changes. I am sometimes able to force my way into the game by clicking the Autosave / Last Save Load button, which launches you into Littleroot Town with a Lv5 starter, but the screen goes black after going through a few warps, seemingly ones that take you to FR as some warps going to CrystalDust seem to work in this workaround as well.

I compared my settings with those used by 360chrism and the only difference I found is that for me the BIOS field says Recommended instead of Loaded. I read the SkyEmu readme and thought you do not need to include a bios file if running in browser, but loading a gba_bios.bin file in addition to the three game roms gives the same problems.

I don't know what I could be doing wrong, and the closest explanation would be some issues caused by running the emulator on MacOS. 

I would appreciate any help with figuring this out and updating the readmes if this is indeed a MacOS support issue.

Thank you

**Comment by KittyPBoxx** [comment]
I suspect the issues is the version of Fire Red. The latest release only supports Fire Red 1.1 (U) . Checksum: (51901a6e40661b3914aa333c802e24e8)

There were two US releases of Fire Red (1.0 and 1.1) and the behavior you describe sounds like what would happen when loading a 1.0 copy. The 0.10.4-Alpha did have partial support for 1.0 (in that it was technically playable) but it had lots of bugs so ultimately I stopped even trying to support it.

As for the bios I do recommend it as a few of the graphical effects don't work without it. The biggest issues is Oak not showing during the intro sequence.

**Comment by michalgorkowski2020** [comment]
Thank you, Kitty!

It's exactly as you said. Using Fire Red Version 1.1 fixed the issue and launched the emulator from the beginning in Pallet Town.

Tested with and without the gba_bios.bin loaded in. The emulator launched in both cases, but did experience the graphic issue of the Oak and Gary sprite not loading in during the intro sequence when not loading in the bios file like you said.

Glad this was an easy fix and not a general MacOS support issue.

Thank you for your hard work developing and supporting this awesome project.
