### ISSUE TITLE
Lost Pkmn Levels Between Games

### ISSUE THREAD

**Issue by llayne321** [KittyPBoxx/GBAXG#6]
My Pokemon lost its levels/EXP when switching into Crystal. I'm attaching a video showing that my Squirtle is Lvl 12 in both FR and Emerald, but when I warp to Crystal (specifically the cafe in Olivine where you get Strength) and check my Pokemon, he's back to Lvl 7. I just started using this randomizer today, and as far as I know I have followed the instructions correctly. This is the only issue I've had so far, but it has happened multiple times. (I couldn't get the bug to happen again earlier, but I was able to recreate it this time to film it.)

https://github.com/KittyPBoxx/GBAXG/assets/148020613/9efd93d5-d994-4ed8-b453-9b69a033f9a0

**Comment by KittyPBoxx** [comment]
That's weird. My guess is that it was too slow copying save data between the games so you ended up with the save data you had when you were last in crystal.

Regular speed was tested quite a bit on to try and make sure that wouldn't happen. So I'm guessing this is either using emulator speedup or the speedup patch from the patches menu is being used? Can you let me know the speed settings you had so I can track down the issue on my machine?

**Comment by llayne321** [comment]
I didn't realize it at the time, but I was using the 2x speed setting on the emulator. I just retried it on the same save using normal speed, and it didn't happen, so I agree it must be something with the speed! I'm not using the "Ultra Speed Codes" patch, just the speed setting on the emulator itself.

**Comment by KittyPBoxx** [comment]
I've pushed a fix that should be on 1.0.4-ALPHA (if it still shows 1.0.3 on the main page you may need to do a hard refresh). Data now gets copied earlier in the process when speedup is on (even though now that means sometimes is makes a copy of the data when it doesn't need to).

Thanks for reporting the issue. Apparently at least 2 other people had the same issue weeks ago but no one mentioned it to me.
